reviewers:
  defaults:
    - nkwangleiGIT
    - bjwswang
    - 0xff-dev
    - Abirdcfly
    - Lanture1064
    - Carrotzpc
    - dayuy
    - huangqg
    - Jandiasnow
    - marsdawe
    - Vsion
    - zggmd

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
    - DNR
    - DO NOT MERGE
    - DNM
    - WIP
    - WORK IN PROCESS
